import type {Metadata} from "next";

import "./globals.css";
import Header from "./header/page";


export const metadata: Metadata = {
    title: "Cola's Cart",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`antialiased`}>
        <Header/>


        {children}
        </body>
        </html>
    );
}
